spring.application.name=GreatRobberyApp
spring.data.mongodb.uri= mongodb+srv://muktadeshmukh_db_user:IlaMl3TXeQxlmopd@cluster0.uipi5vh.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=robberydb